#define THREAD_GROUP_SIZE_X 4
#define THREAD_GROUP_SIZE_Y 4
#define THREAD_GROUP_SIZE_Z 1

int InputResolutionSquare;

RWTexture2D<float4> Input;
RWTexture2D<float4> Output;

#pragma kernel FlipRenderTarget
[numthreads(THREAD_GROUP_SIZE_X, THREAD_GROUP_SIZE_Y, THREAD_GROUP_SIZE_Z)]
void FlipRenderTarget(uint3 id : SV_DispatchThreadID)
{
    //NOTE: need to offset by -1 otherwwise we will get a black border
    Output[id.xy] = Input[uint2(id.x, (InputResolutionSquare - 1) - id.y)];
}